// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Prova.Tests.ForTestable
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Can provide different ways of supplying a dependency to a class with a single dep" +
        "endency")]
    public partial class CanProvideDifferentWaysOfSupplyingADependencyToAClassWithASingleDependencyFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SingleDependency.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Can provide different ways of supplying a dependency to a class with a single dep" +
                    "endency", "In order to be able to use testable objects\nAs a developer\nI want to be able to s" +
                    "upply different types of dependencies", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Implicitly obtain a dependency from the loaded assemblies")]
        [NUnit.Framework.CategoryAttribute("Single_Dependency")]
        public virtual void ImplicitlyObtainADependencyFromTheLoadedAssemblies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Implicitly obtain a dependency from the loaded assemblies", new string[] {
                        "Single_Dependency"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have a testable HasSingleDependency");
#line 9
 testRunner.When("I use the testable object");
#line 10
 testRunner.Then("I should have a dependency of type CannedDependency");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Specify an explicit dependency to use")]
        [NUnit.Framework.CategoryAttribute("Single_Dependency")]
        public virtual void SpecifyAnExplicitDependencyToUse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Specify an explicit dependency to use", new string[] {
                        "Single_Dependency"});
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I have a testable HasSingleDependency");
#line 15
 testRunner.When("I tell the testable object to use an explicit dependency");
#line 16
 testRunner.And("I use the testable object");
#line 17
 testRunner.Then("I should have an instance that uses that explicit dependency");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Specify a default dependency to use on all testable instances")]
        [NUnit.Framework.CategoryAttribute("Single_Dependency")]
        public virtual void SpecifyADefaultDependencyToUseOnAllTestableInstances()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Specify a default dependency to use on all testable instances", new string[] {
                        "Single_Dependency"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("I want to use a default dependency");
#line 22
 testRunner.And("I have a testable HasSingleDependency");
#line 23
 testRunner.And("I have another testable HasSingleDependency");
#line 24
 testRunner.When("I use the testable object");
#line 25
 testRunner.And("I use the other testable object");
#line 26
 testRunner.Then("The two instances should have different dependencies");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
